from typing import Annotated

import numpy
from numpy.typing import NDArray


class Box:
    def __init__(self, x0: float, y0: float, z0: float, Lx: float, Ly: float, Lz: float) -> None: ...

    def cx(self) -> float: ...

    def cy(self) -> float: ...

    def cz(self) -> float: ...

    def contains(self, x: float, y: float, z: float) -> bool: ...

    def volume(self) -> float: ...

    @property
    def x0(self) -> float: ...

    @x0.setter
    def x0(self, arg: float, /) -> None: ...

    @property
    def y0(self) -> float: ...

    @y0.setter
    def y0(self, arg: float, /) -> None: ...

    @property
    def z0(self) -> float: ...

    @z0.setter
    def z0(self, arg: float, /) -> None: ...

    @property
    def Lx(self) -> float: ...

    @Lx.setter
    def Lx(self, arg: float, /) -> None: ...

    @property
    def Ly(self) -> float: ...

    @Ly.setter
    def Ly(self, arg: float, /) -> None: ...

    @property
    def Lz(self) -> float: ...

    @Lz.setter
    def Lz(self, arg: float, /) -> None: ...

class Domain:
    def __init__(self, domain_box: Box, mass: float, W: float, molecule_size: float, scale_factor: float, time_scale_factor: float) -> None: ...

    def generateParticles(self, n_density: float, T: float, x_min: float, x_max: float) -> None: ...

    def generateMesh(self) -> None: ...

    def makeCellList(self) -> None: ...

    def updateCellList(self) -> None: ...

    def applyPeriodicBoundaries(self, px: bool, py: bool, pz: bool) -> None: ...

    def moveParticles(self) -> None: ...

    def collideParticles(self) -> None: ...

    def saveXYZ(self, file_name: str) -> None: ...

    def computeFlowProperties(self) -> None: ...

    def printStatsHeader(self) -> None: ...

    def printStats(self, time: float) -> None: ...

    def writeVTU(self, file_name: str) -> None: ...

    def getTimeStep(self) -> float: ...

    def writeXProfile(self, file_name: str) -> None: ...

    def addWall(self, wall: Wall) -> None: ...

class Wall:
    def __init__(self, position: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], normal: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], size: Annotated[NDArray[numpy.float64], dict(shape=(2), order='C')], velocity: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')] = ..., Tw: float = 0.0) -> None: ...

    def setVelocity(self, velocity: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]) -> None: ...

    def getCenterPosition(self) -> Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')]: ...

class DiffuseWall(Wall):
    def __init__(self, position: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], normal: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], size: Annotated[NDArray[numpy.float64], dict(shape=(2), order='C')], velocity: Annotated[NDArray[numpy.float64], dict(shape=(3), order='C')], Tw: float) -> None: ...
